version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-demo_key}
      - PINECONE_API_KEY=${PINECONE_API_KEY:-your_pinecone_key_here}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME:-partselect-parts}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_key_here}
    volumes:
      - ./backend:/app
      - ./data:/app/data
    restart: unless-stopped